# Generated by Django 4.2.23 on 2025-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_frameresult_videoanalysis_delete_detectionfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='loginid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table=None,
        ),
    ]
